info:
  concrete-type: auction-service

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/app_db # database es el nombre del docker
    username: admin_user
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5  # optimización de RAM, no quiero que se sature la base de datos
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update # crea las tablas automáticamente si no existen
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  file:
    name: logs/auctions.log
