spring:
  boot:
    admin:
      client:
        url: "http://localhost:9090/admin"
  application:
    name: ai-service-local
  config:
    import: "optional:configserver:http://localhost:8888"

logging:
  file:
    name: logs/ai-service.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
      post:
        enabled: true

nats:
  url: nats://localhost:4222

openrouter:
  api:
    url: https://openrouter.ai/api/v1/chat/completions
    key: ${OPENROUTER_API_KEY}

server:
  port: 7085
