spring:
  application:
    name: auction-service
  boot:
    admin:
      client:
        url: "http://admin-server:9090/admin"
  config:
    import: "optional:configserver:http://config-service-v3:8888"
  datasource:
    url: jdbc:mariadb://mariadb:3306/app_db
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5  # optimización de RAM, no quiero que se sature la base de datos
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update # crea las tablas automáticamente si no existen
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: /app/logs/auctions.log

nats:
  url: nats://nats-server:4222
auction:        #Ojo, parece tener un rate limiter...
  scraper:
    delay:
      min: 500
      max: 1000
server:
  port: 8081

