info:
  config-source: "local"
  env-type: "local"

spring:
  application:
    name: orchestrator-local
  config:
    import: "optional:configserver:http://localhost:8888"
  boot:
    admin:
      client:
        url: "http://localhost:9090/admin"
  cloud:
    config:
      override-none: false
      allow-override: true
      override-system-properties: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
      post:
        enabled: true

nats:
  url: nats://localhost:4222
  durable-name: OrchestratorService
  subjects:
    wildcards:
      auctions: auctions.>
      properties: properties.>
      ai: ai.>
    publisher:
      auctions: auctions.get
      properties: properties.get
      ai: ai.get
    subscriber:
      auctions: auctions.response
      properties: properties.response
      ai: ai.response
  streams:
    auctions: AUCTIONS_STREAM
    properties: PROPERTIES_STREAM
    ai: AI_STREAM

logging:
  file:
    name: logs/orchestrator.log

schedules:
  auctions:
    get-auctions:
      cron: "0 0 0 * * ?" # las doce de la noche


server:
  port: 7082